development work

diff --git a/tool_shared/bespoke/env b/tool_shared/bespoke/env
--- a/tool_shared/bespoke/env
+++ b/tool_shared/bespoke/env
@@ -5,6 +5,12 @@ if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
   exit 1
 fi
 
+# without this bash takes non-matching globs literally
+shopt -s nullglob
+
+# does not presume sharing or world permissions
+umask 0077
+
 # --------------------------------------------------------------------------------
 # project definition
 
@@ -26,10 +32,33 @@ fi
   # set the prompt decoration to the name of the project
   PROMPT_DECOR=$PROJECT
 
+  export REPO_HOME PROJECT PROMPT_DECOR
+
 # --------------------------------------------------------------------------------
-# The project administrator sets up the following tools for all roles to use:
+# Project wide Tool setup
 #
-  export JAVA_HOME="$REPO_HOME/tool_shared/third_party/jdk-11"
+
+export VIRTUAL_ENV="$REPO_HOME/tool_shared/third_party/Python"
+export PYTHON_HOME="$VIRTUAL_ENV"
+unset PYTHONHOME
+
+
+# --------------------------------------------------------------------------------
+# PATH
+#   precedence: last defined, first discovered
+  
+  PATH="$REPO_HOME/tool_shared/third_party/RT-project-share/release/bash:$PATH"
+  PATH="$REPO_HOME/tool_shared/third_party/RT-project-share/release/amd64:$PATH"
+  PATH="$REPO_HOME/tool_shared/third_party:$PATH"
+  PATH="$REPO_HOME/tool_shared/customized:$PATH"
+  PATH="$REPO_HOME"/tool_shared/bespoke:"$PATH"
+
+  # Remove duplicates
+  clean_path() {
+    PATH=$(echo ":$PATH" | awk -v RS=: -v ORS=: '!seen[$0]++' | sed 's/^://; s/:$//')
+  }
+  clean_path
+  export PATH
 
 # --------------------------------------------------------------------------------
 # the following functions are provided for other scripts to use.
@@ -52,14 +81,50 @@ fi
     dirname "$(script_fp)"
   }
 
-# --------------------------------------------------------------------------------
-# Exports
-# Bash has no 'closure' hence when exporting a function, one must also export all the pieces.
-# do not export script_afp
-
-  export REPO_HOME PROJECT PROMPT_DECOR
   export -f script_adp script_fn script_dp script_fp
 
-  export ENV=$(script_fp)
-  echo ENV "$ENV"
+#--------------------------------------------------------------------------------
+# used by release scripts
+#
+
+  install_file() {
+    if [ "$#" -lt 3 ]; then
+      echo "env::install_file usage: install_file <source1> <source2> ... <target_dir> <permissions>"
+      return 1
+    fi
+
+    perms="${@: -1}"         # Last argument is permissions
+    target_dp="${@: -2:1}"   # Second-to-last argument is the target directory
+    sources=("${@:1:$#-2}")  # All other arguments are source files
+
+    if [ ! -d "$target_dp" ]; then
+      echo "env::install_file no install done: target directory '$target_dp' does not exist."
+      return 1
+    fi
+
+    for source_fp in "${sources[@]}"; do
+      if [ ! -f "$source_fp" ]; then
+        echo "env::install_file: source file '$source_fp' does not exist."
+        return 1
+      fi
+
+      target_file="$target_dp/$(basename "$source_fp")"
+
+      if ! install -m "$perms" "$source_fp" "$target_file"; then
+        echo "env::install_file: Failed to install $(basename "$source_fp") to $target_dp"
+        return 1
+      else
+        echo "env::install_file: installed $(basename "$source_fp") to $target_dp with permissions $perms"
+      fi
+    done
+  }
+
+  export -f install_file
+
+# --------------------------------------------------------------------------------
+# closing
+#
+  if [[ -z "$ENV" ]]; then
+    export ENV=$(script_fp)
+  fi
 
